# Support Vector Regression (SVR)

In [155]:
########PROBLEMAS NO LINEALES 
#en este caso es útil emplear SVR porque se trata de un problema no lineal (datos no distribuidos) y la regresión lineal no funciona

## Importing the libraries

In [156]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [157]:
dataset = pd.read_csv('Data.csv')
dataset.head() 

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [158]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [159]:
print(X)
print(y)

[[  41.76 1024.07   73.17]
 [  62.96 1020.04   59.08]
 [  39.4  1012.16   92.14]
 ...
 [  74.33 1012.92   36.48]
 [  69.45 1013.86   62.39]
 [  62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [160]:
y = y.reshape(len(y),1)
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


## Splitting the dataset into the Training set and Test set

In [161]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [162]:
#es necesario estandarizar los datos
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [163]:
print(X_train)

[[-0.89  0.67  0.52]
 [-0.01  0.45  0.15]
 [ 1.85  0.24 -1.88]
 ...
 [-1.25  0.85  0.13]
 [-1.04  1.55  0.88]
 [ 1.06 -1.2  -2.42]]


In [164]:
print(y_train)

[[ 1.15]
 [ 0.8 ]
 [-1.31]
 ...
 [ 0.28]
 [ 0.49]
 [-1.54]]


## Training the SVR model on the whole dataset

In [165]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf') #Gaussian Radial Basis Function
regressor.fit(X_train, y_train)

regressor2 = SVR(kernel = 'rbf')
regressor2.fit(X, y)

C:\Users\pbartolome\AppData\Local\anaconda\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pbartolome\AppData\Local\anaconda\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the results

In [166]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.08 431.23]
 [460.83 460.01]
 [468.61 461.14]
 ...
 [468.81 473.26]
 [442.18 438.  ]
 [464.51 463.28]]


## Predicting a new result

In [167]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])).reshape(-1,1))

ValueError: X has 1 features, but StandardScaler is expecting 3 features as input.

## Visualising the SVR results

In [ ]:
plt.scatter(sc_X.inverse_transform(X), sc_y.inverse_transform(y), color = 'red')
plt.plot(sc_X.inverse_transform(X), sc_y.inverse_transform(regressor.predict(X).reshape(-1,1)), color = 'blue')
plt.title('Truth or Bluff (SVR)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

## Visualising the SVR results (for higher resolution and smoother curve)

In [ ]:
X_grid = np.arange(min(sc_X.inverse_transform(X)), max(sc_X.inverse_transform(X)), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(sc_X.inverse_transform(X), sc_y.inverse_transform(y), color = 'red')
plt.plot(X_grid, sc_y.inverse_transform(regressor.predict(sc_X.transform(X_grid)).reshape(-1,1)), color = 'blue')
plt.title('Truth or Bluff (SVR)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred) #se debería hacer sobre un mismo dataset para todos los casos